name: alamoody
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  # easy_splash_screen: ^1.0.4
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  # flutter_native_splash:
  gradient_borders: ^1.0.1
  device_preview: ^1.2.0
  # adaptive_theme: ^3.1.1
  flutter_svg: ^1.1.6
  carousel_slider: ^5.0.0
  contained_tab_bar_view: ^0.8.0
  dots_indicator: ^3.0.0
  syncfusion_flutter_gauges: ^20.3.50
  share_plus: ^10.1.3
  cached_network_image:
  dio: ^5.7.0 
  dio_http_formatter: ^3.3.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  fluttertoast: ^8.2.10
  validators: ^3.0.0
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  flutter_rounded_date_picker: ^3.0.4
  flutter_screenutil: any
  provider: ^6.1.2
  # speech_to_text: ^6.1.1
  # sliver_header_delegate: ^0.0.5
  flutter_phoenix: ^1.1.1
  country_code_picker: ^3.1.0
  sms_autofill: ^2.4.1 
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.2
  firebase_core: ^3.10.1 
  firebase_auth: ^5.4.1
  flutter_facebook_auth: ^7.1.1
  

  open_filex: ^4.6.0
  url_launcher: ^6.3.1 
  # collection: ^1.19.1
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.1
  intl: ^0.19.0
  rxdart: ^0.27.7
  webview_flutter: ^4.10.0

  # webviewx:
  # zego_uikit_prebuilt_live_streaming: ^2.3.8

  flutter_native_splash: ^2.4.4
  google_mobile_ads: ^5.3.1
  # persistent_bottom_nav_bar: ^5.0.2
  zego_uikit_signaling_plugin: ^2.8.9
  # remove_bg: ^0.0.1
  just_audio: ^0.9.44
  audio_service: ^0.18.16
  firebase_dynamic_links: ^6.1.1
  just_audio_background: ^0.0.1-beta.14
  # flutter_sizer: ^1.0.5
  # responsive_builder: ^0.6.4
  rename_app: ^1.6.2
  percent_indicator: ^4.2.4
  connectivity_plus: ^6.1.3

dependency_overrides:
  zego_uikit_prebuilt_live_streaming: ^3.13.12

  modal_bottom_sheet: ^3.0.0-pre
  flutter_lints: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner: ^2.3.2
  # easy_splash_screen: ^1.0.4
  hive_generator: ^2.0.0
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: assets/images/logo.png
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleToFill
  android_12:
    image: assets/images/logo.png
    color: "#000000"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - lang/en.json
    - lang/ar.json
    - assets/images/icons_png/
    - assets/images/alamoody-logo.png
    - assets/images/default_user_icon.png
    - assets/images/popular-border.png
    - assets/images/popular-unselected-border.png
    - assets/images/premium-image.png
    - assets/images/player-BG.png
    - assets/images/mood_border.png
    - assets/images/logo.png 
    - assets/images/small_logo.png 


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Black.ttf
        - asset: assets/font/poppins/Poppins-BlackItalic.ttf
        - asset: assets/font/poppins/Poppins-Bold.ttf
        - asset: assets/font/poppins/Poppins-BoldItalic.ttf
        - asset: assets/font/poppins/Poppins-BoldItalic.ttf
        - asset: assets/font/poppins/Poppins-ExtraBold.ttf
        - asset: assets/font/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/font/poppins/Poppins-ExtraLight.ttf
        - asset: assets/font/poppins/Poppins-Italic.ttf
        - asset: assets/font/poppins/Poppins-Light.ttf
        - asset: assets/font/poppins/Poppins-Medium.ttf
        - asset: assets/font/poppins/Poppins-Regular.ttf
        - asset: assets/font/poppins/Poppins-SemiBold.ttf
        - asset: assets/font/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/font/poppins/Poppins-ThinItalic.ttf


      