import '../entities/user.dart';

class UserModel extends User {
  const UserModel({
    required super.id,
    required super.name,
    required super.username,
    required super.soundcloudUrl,
    required super.instagramUrl,
    required super.youtubeUrl,
    required super.facebookUrl,
    required super.twitterUrl,
    required super.websiteUrl,
    required super.artistId,
    required super.collectionCount,
    required super.followingCount,
    required super.followerCount,
    required super.notification,
    required super.bio,
    required super.allowComments,
    required super.commentCount,
    required super.image,
    required super.artworkUrl,
    required super.permalinkUrl,
    required super.favorite,
  });
  factory UserModel.fromJson(Map<String, dynamic> json) => UserModel(
        id: json['id'],
        name: json['name'],
        username: json['username'],
        soundcloudUrl: json['soundcloud_url'],
        instagramUrl: json['instagram_url'],
        youtubeUrl: json['youtube_url'],
        facebookUrl: json['facebook_url'],
        twitterUrl: json['twitter_url'],
        websiteUrl: json['website_url'],
        artistId: json['artist_id'],
        collectionCount: json['collection_count'],
        followingCount: json['following_count'],
        followerCount: json['follower_count'],
        notification: json['notification'],
        bio: json['bio'],
        allowComments: json['allow_comments'],
        commentCount: json['comment_count'],
        image: json['image'],
        artworkUrl: json['artwork_url'],
        permalinkUrl: json['permalink_url'],
        favorite: json['favorite'],
      );
}
